version: "3.1"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
            - ./logs:/var/www/logs/
            - ./php-ini:/usr/local/etc/php/custom.d
        environment:
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
        links:
            - db
        networks:
            - default
    db:
        image: mariadb
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --sql-mode=""
        environment:
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: root 
            UPLOAD_LIMIT: 1280000000
volumes:
    persistent:
